version: '3'

services:
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/powerdash/
        ports:
            - 8000:8000
        env_file:
            - ./.env.dev
        depends_on: 
            - db
    db:
        image: postgres
        ports: 
            - "5432:5432"
        volumes:
            - pg_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=maek
            - POSTGRES_PASSWORD=maek
            - POSTGRES_DB=test_db
volumes:
    pg_data: